### PR TITLE
Html view

### PR DESCRIPTION
**Pull request by tiktuk**
Made a simple web interface for Podcats :) . And started to use separate Jinja2 templates for rendering.

### CODE REVIEW

**Comment by jakubroztocil** [comment]
nice 😄

**Comment by jakubroztocil** [comment]
@tiktuk maybe also update the README?

**Comment by tiktuk** [comment]
Good idea, will do :) . Shouldn't we up the version too?

**Comment by jakubroztocil** [comment]
:+1:

**Pull request merged**
